# ╔─────────────────────────────────────────────────────────────╗
# │ ____  ____ ____ ___   ____  _  ______  ___ ____ _____ ____  │
# │|  _ \| __ ) ___|_ _| / ___|| |/ /  _ \|_ _|  _ \_   _/ ___| │
# │| |_) |  _ \___ \| |  \___ \| ' /| |_) || || |_) || | \___ \ │
# │|  __/| |_) |__) | |   ___) | . \|  _ < | ||  __/ | |  ___) |│
# │|_|   |____/____/___| |____/|_|\_\_| \_\___|_|    |_| |____/ │
# ╚─────────────────────────────────────────────────────────────╝
#Currently the Skript is designed to be used on Advanced Ban, if you would like it to work on other punishment plugins you'll need to configure it yourself!
#IN DEVELOPMENT DO NOT USE ON SERVERS IF YOU'RE NOT WILLING TO FIX THE SKRIPT YOURSELF!
#Version 0.8.51
options:
    actionbar: true #Set this to false to disable the action bar whilst in staff mode
    vanish: false #Enable this if using our vanish addon! Otherwise the command labeled "vanishcommand" will be used :D 
    pvp: false #Whether to allow pvp whilst in staff mode
    vanishcommand: "vanish" #Set this to your vanish command if not using our vanish addon!
    freezecommand: "freeze %{_target}%"
    sound: "entity.experience_orb.pickup"
    errorsound: "block.anvil.place"

# ╔───────────────────────────────────────────╗
# │__        __               _             _ │
# │\ \      / /_ _ _ __ _ __ (_)_ __   __ _| |│
# │ \ \ /\ / / _` | '__| '_ \| | '_ \ / _` | |│
# │  \ V  V / (_| | |  | | | | | | | | (_| |_|│
# │   \_/\_/ \__,_|_|  |_| |_|_|_| |_|\__, (_)│
# │                                   |___/   │
# ╚───────────────────────────────────────────╝
#The following is the code for the skript! Modifying this is required (Built In Configurator coming soon!) in some cases, however can break things realllyyyy quickly!
#If you need help on configuring shoot me a DM on Discord (pbsi) ! 
#The punishment type set in functions must be kept the same for it to display in /punishments ! (You can change that yourself if you'd like ;) 


#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------#


# ╔───────────────────────────────────────────────╗
# │ _____                 _   _                 _ │
# │|  ___|   _ _ __   ___| |_(_) ___  _ __  ___| |│
# │| |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __| |│
# │|  _|| |_| | | | | (__| |_| | (_) | | | \__ \_|│
# │|_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___(_)│
# ╚───────────────────────────────────────────────╝


function punishbugabuse(target: offline player, sender: player):
    add 1 to {punishments.%{_target}'s uuid%}
    set {_ap} to {punishments.%{_target}'s uuid%}
    set {punishments.%{_target}'s uuid%.type.%{_ap}%} to "BugAbuse"
    set {punishments.%{_target}'s uuid%.Executor.%{_ap}%} to {_sender}'s name
    set {punishments.%{_target}'s uuid%.date.%{_ap}%} to now
    if {punishments.%{_target}'s uuid%} is 1:
        if {pb.1} is not set:
            set {pb.1} to "tempban %{_target}'s name% 1w Bug Abuse"
        execute {_sender} command {pb.1}
    if {punishments.%{_target}'s uuid%} is 2:
        if {pb.2} is not set:
            set {pb.2} to "tempban %{_target}'s name% 1mo Bug Abuse"
        execute {_sender} command {pb.2}
    if {punishments.%{_target}'s uuid%} is greater than 2:
        if {pb.3} is not set:
            set {pb.p3} to "tempban %{_target}'s name% 3mo Bug Abuse"
        execute {_sender} command {pb.3}
    send "&cPunish &8| &cSuccessfully punished &4%{_target}'s name%&c!" to {_sender}

function punishspam(target: offline player, sender: player):
    add 1 to {punishments.%{_target}'s uuid%}
    set {_ap} to {punishments.%{_target}'s uuid%}
    set {punishments.%{_target}'s uuid%.type.%{_ap}%} to "Spam"
    set {punishments.%{_target}'s uuid%.Executor.%{_ap}%} to {_sender}'s name
    set {punishments.%{_target}'s uuid%.date.%{_ap}%} to now
    if {punishments.%{_target}'s uuid%} is 1:
        if {ps.1} is not set:
            set {ps.1} to "tempmute %{_target}'s name% 1h Spam"
        execute {_sender} command {ps.1}
        stop
    if {punishments.%{_target}'s uuid%} is 2:
        if {ps.2} is not set:
            set {ps.2} to "tempmute %{_target}'s name% 12h Spam"
        execute {_sender} command {ps.2}
        stop
    if {punishments.%{_target}'s uuid%} is greater than 2:
        if {ps.3} is not set:
            set {ps.3} to "tempmute %{_target}'s name% 1d Spam"
        execute {_sender} command {ps.3}

    send "&cPunish &8| &cSuccessfully punished &4%{_target}'s name%&c!" to {_sender}

function punishhacker(target: offline player, sender: player):
    add 1 to {punishments.%{_target}'s uuid%}
    set {_ap} to {punishments.%{_target}'s uuid%}
    set {punishments.%{_target}'s uuid%.type.%{_ap}%} to "Cheating"
    set {punishments.%{_target}'s uuid%.Executor.%{_ap}%} to {_sender}'s name
    set {punishments.%{_target}'s uuid%.date.%{_ap}%} to now
    if {punishments.%{_target}'s uuid%} is 1:
        if {ph.1} is not set:
            set {ph.1} to "tempban %{_target}'s name% 1mo Cheating"
        execute {_sender} command {ph.1}
    if {punishments.%{_target}'s uuid%} is 2:
        if {ph.2} is not set:
            set {ph.2} to "tempban %{_target}'s name% 3mo Cheating"
        execute {_sender} command {ph.2}
    if {punishments.%{_target}'s uuid%} is greater than 2:
        if {ph.3} is not set:
            set {ph.3} to "ban %{_target}'s name% Cheating"
        execute {_sender} command {ph.3}
    send "&cPunish &8| &cSuccessfully punished &4%{_target}'s name%&c!" to {_sender}

function punishxrayer(target: offline player, sender: player):
    add 1 to {punishments.%{_target}'s uuid%}
    set {_ap} to {punishments.%{_target}'s uuid%}
    set {punishments.%{_target}'s uuid%.type.%{_ap}%} to "Xray"
    set {punishments.%{_target}'s uuid%.Executor.%{_ap}%} to {_sender}'s name
    set {punishments.%{_target}'s uuid%.date.%{_ap}%} to now
    if {punishments.%{_target}'s uuid%} is 1:
        if {px.1} is not set:
            set {px.1} to "tempban %{_target}'s name% 15d X-Ray"
        execute {_sender} command {px.1}
        stop
    if {punishments.%{_target}'s uuid%} is 2:
        if {px.2} is not set:
            set {px.2} to "tempban %{_target}'s name% 1mo X-Ray"
        execute {_sender} command {px.2}
        stop
    if {punishments.%{_target}'s uuid%} is greater than 2:
        if {px.3} is not set:
            set {px.3} to "tempban %{_target}'s name% 3mo X-Ray"
        execute {_sender} command {px.3}
        stop



# ╔────────────────────────────────────────────────────────╗
# │  ____                                          _     _ │
# │ / ___|___  _ __ ___  _ __ ___   __ _ _ __   __| |___| |│
# │| |   / _ \| '_ ` _ \| '_ ` _ \ / _` | '_ \ / _` / __| |│
# │| |__| (_) | | | | | | | | | | | (_| | | | | (_| \__ \_|│
# │ \____\___/|_| |_| |_|_| |_| |_|\__,_|_| |_|\__,_|___(_)│
# ╚────────────────────────────────────────────────────────╝


command punish <offlineplayer>:
    permission: staff.member
    trigger:
        set {punishedplayer.%player's uuid%} to arg-1's name
        set {_pgui} to a new chest inventory with 3 rows named "&cPunish Player"
        set slot 10 of {_pgui} to a anvil named "&c&lHacking"
        set slot 12 of {_pgui} to a iron pickaxe named "&c&lXray"
        set slot 14 of {_pgui} to a hopper named "&c&lBug Abusing"
        set slot 16 of {_pgui} to a book and quill named "&c&lChat Abuse"
        open {_pgui} to player

            

command lockaccount <offlineplayer>:
    permission: staff.member
    trigger:
        if arg-1 does not have permission "staff.member":
            if {lockedaccounts::*} does not contain arg-1's uuid:
                add arg-1's uuid to {lockedaccounts::*}
                send "&cLock &8| &cSuccessfully locked &4%arg-1's name%'s &caccount" to player
                kick arg-1 due to "&cAccount Locked!"
                play sound {@sound} with volume 0.5 and pitch 2 at player 
            else:
                send "&cError &8| &4%arg-1's name%'s&c account has already been locked!"
                play sound {@errorsound} with volume 2 and pitch 1 at player
        else:
            send "&cError &8|&c You cannot lock a &4staff member&c's account!"
            play sound {@errorsound} with volume 2 and pitch 1 at player
command unlockaccount <offlineplayer>:
    permission: staff.member
    trigger:
        if {lockedaccounts::*} contains arg-1's uuid:
            remove arg-1's uuid from {lockedaccounts::*}
            send "&2Unlock &8| &2Successfully unlocked &a%arg-1's name%'s &2account" to player
            play sound {@sound} with volume 0.5 and pitch 2 at player 
        else:
            send "&cError &8| &4%arg-1's name%'s&c account isn't locked!"
            play sound {@errorsound} with volume 2 and pitch 1 at player


command resetpunishments <offlineplayer>:
    permission: staff.admin
    trigger:
        loop {punishments.%arg-1's uuid%} times:
            add 1 to {_ap}
            delete {punishments.%arg-1's uuid%.type.%{_ap}%}
            delete {punishments.%arg-1's uuid%.Executor.%{_ap}%}
            delete {punishments.%arg-1's uuid%.date.%{_ap}%}
        delete {punishments.%arg-1's uuid%} 
        send "&bReset &8|&b Successfully reset &3%arg-1's name%'s&b punishments!" to player
command punishments <offline player>:
    permission: staff.member
    trigger:
        add 1 to {_values}
        set {_plist} to a new chest inventory with 5 rows named "&cPast Punishments"
        loop {punishments.%arg-1's uuid%} times:
            if {punishments.%arg-1's uuid%.type.%{_values}%} is "Cheating":
                set slot {_values} of {_plist} to a red wool named "&c&lCheating-Ban" with lore "&8Date: &c%{punishments.%arg-1's uuid%.date.%{_values}%}%" and "&8Executor: &c%{punishments.%arg-1's uuid%.Executor.%{_values}%}%"
            if {punishments.%arg-1's uuid%.type.%{_values}%} is "Xray":
                set slot {_values} of {_plist} to a orange wool named "&c&lXray-Ban" with lore "&8Date: &c%{punishments.%arg-1's uuid%.date.%{_values}%}%" and "&8Executor: &c%{punishments.%arg-1's uuid%.Executor.%{_values}%}%"
            if {punishments.%arg-1's uuid%.type.%{_values}%} is "BugAbuse":
                set slot {_values} of {_plist} to a pink wool named "&c&lBug Abuse-Ban" with lore "&8Date: &c%{punishments.%arg-1's uuid%.date.%{_values}%}%" and "&8Executor: &c%{punishments.%arg-1's uuid%.Executor.%{_values}%}%"
            if {punishments.%arg-1's uuid%.type.%{_values}%} is "Spam":
                set slot {_values} of {_plist} to a yellow wool named "&c&lSpam-Mute" with lore "&8Date: &c%{punishments.%arg-1's uuid%.date.%{_values}%}%" and "&8Executor: &c%{punishments.%arg-1's uuid%.Executor.%{_values}%}%"
            add 1 to {_values}
        set slot 0 of {_plist} to arg-1's head named "&c&l%arg-1%'s Punishments" with lore "&8UUID:&c %arg-1's uuid%" and "&8First Join:&c %{sm::%arg-1's uuid%.joindate}%" and "&8Last Join:&c %{sm::%arg-1's uuid%.lastjoin}%"
        open {_plist} to player

command staffmode:
    permission: staff.member
    trigger:
        if {staffmode::*} doesn't contain player's uuid:
            clear player's inventory
            set slot 1 of player's inventory to a ice named "&b&lFreeze Player" with lore "&7Right Click on a player to freeze them"
            set slot 0 of player's inventory to a diamond axe named "&c&lBan Hammer" with lore "&7Right click on a player to punish them!"
            add player's uuid to {staffmode::*}
            if {@vanish} is true:
                if {vanish.%player's uuid%} is not true:
                    execute player command "vanish"
                set slot 8 of player's inventory to a light green dye named "&a&lVanish" with lore "&7Status: &aEnabled"
            else:
                set slot 8 of player's inventory to a potion of invisibility named "&f&lVanish" with lore "&3Right click&b to use!"
        else:
            clear player's inventory
            remove player's uuid from {staffmode::*}
            if {@actionbar} is true:
                send actionbar "" to player

command filter <text> [<text>]: #Todo: Make filter GUI! :D
    permission: staff.admin
    trigger:
        if arg-1 is not "add" or "list" or "remove":
            send "&cError &8| &cInvalid subcommand, please use &4add&c, &4list&c, or &4remove&c!"
            play sound {@errorsound} with volume 2 and pitch 1 at player
        if arg-1 is "add":
            if arg-2 is not set:
                send "&cError &8| &cPlease type the text to &4add&c to the filter!"
                play sound {@errorsound} with volume 2 and pitch 1 at player
            else:
                if {filter::*} doesn't contain arg-2:
                    send "&bSuccessfully added &3%arg-2 in proper case%&b to the filter!" to player
                    play sound {@sound} with volume 0.5 and pitch 2 at player 
                    add arg-2 in proper case to {filter::*}
                else:
                    send "&cError &8| &cThe filter already contains &4%arg-2%&c!"
                    play sound {@errorsound} with volume 2 and pitch 1 at player
        if arg-1 is "remove":
            if arg-2 is not set:
                send "&cError &8| &cPlease type the text to &4remove&c from the filter!"
                play sound {@errorsound} with volume 2 and pitch 1 at player
            else:
                if {filter::*} contains arg-2:
                    send "&bSuccessfully removed &3%arg-2%&b from the filter!" to player
                    play sound {@sound} with volume 0.5 and pitch 2 at player 
                    remove arg-2 from {filter::*}
                else:
                    send "&cError &8| &cThe filter does not contains &4%arg-2%&c!"
                    play sound {@errorsound} with volume 2 and pitch 1 at player
        if arg-1 is "list":
            if {filter::*} is set:
                send "&3&l💬&r&b Filter List&3:"
                loop {filter::*}:
                    add 1 to {_count}
                    send "&b%{_count}%. &8| &3%loop-value%"
                play sound {@sound} with volume 0.5 and pitch 2 at player 
            else:
                send "&eWarn &8| &eThe filter is &6empty&e!"
                play sound {@errorsound} with volume 1 and pitch 1 at player
command freeze <player>:
    permission: staff.member
    trigger:
        if arg-1 does not have permission "staff.member":
            if {freeze.%arg-1's uuid%} is not true:
                send "&cAlert &8|&c You have been &4frozen&c!" to arg-1
                send "&2Success &8| &2Successfully froze &a%arg-1's name%&2!" to player
                set {freeze.%arg-1's uuid%} to true
            else:
                send "&cAlert &8|&c You have been &4unfrozen&c!" to arg-1
                set {freeze.%arg-1's uuid%} to false
                send "&2Success &8| &2Successfully unfroze &a%arg-1's name%&2!" to player
        else:
            send "&eWarn &8|&e The target player has is a &6staff member&e!" to player
            play sound {@errorsound} with volume 1 and pitch 1 at player


# ╔─────────────────────────────────╗
# │ _____                 _       _ │
# │| ____|_   _____ _ __ | |_ ___| |│
# │|  _| \ \ / / _ \ '_ \| __/ __| |│
# │| |___ \ V /  __/ | | | |_\__ \_|│
# │|_____| \_/ \___|_| |_|\__|___(_)│
# ╚─────────────────────────────────╝


on connect:
    if {lockedaccounts::*} contains player's uuid:
        kick player due to "&8[&cLocked Account&8]%nl%&cPlease contact an &8[&cAdmin&8]&c to resolve this."
on inventory click:
    if name of event-inventory is "&cPunish Player":
        if index of event-slot = 10: 
            punishhacker({punishedplayer.%player's uuid%} parsed as offline player, player)
        if index of event-slot = 12: 
            punishxrayer({punishedplayer.%player's uuid%} parsed as offline player, player)
        if index of event-slot = 14:
            set {_bagui} to a new chest inventory with 3 rows named "&c&lBug Abusing"
            set slot 11 of {_bagui} to a hopper named "&c&lDuping"
            set slot 13 of {_bagui} to a redstone block named "&c&lBlock Glitching" with lore "&8And other glitches that give an advantage"
            set slot 15 of {_bagui} to a book named "&c&lGeneral Bug Usage" with lore "&8Failing to report meaningful bugs."
            open {_bagui} to player
        if index of event-slot = 16:
            set {_cagui} to a new chest inventory with 3 rows named "&c&lChat Abuse"
            set slot 11 of {_cagui} to a book named "&c&lSpam"
            set slot 13 of {_cagui} to a barrier named "&c&lRacism" with lore "&8And anything else discriminatory to a player"
            set slot 15 of {_cagui} to a compass named "&c&lDoxxing/DDoSing Threats" with lore "&8This includes any threats to do anything that is a crime."
            open {_cagui} to player
    if name of event-inventory is "&c&lBug Abusing":
        if index of event-slot = 11:
            execute player command "lockaccount %{punishedplayer.%player's uuid%}%"
        if index of event-slot = 13:
            punishbugabuse({punishedplayer.%player's uuid%} parsed as offline player, player)
        if index of event-slot = 15:
            execute player command "tempban %{punishedplayer.%player's uuid%}% 1h Failure to report bugs."
    if name of event-inventory is "&c&lChat Abuse":
        if index of event-slot = 11:
            punishspam({punishedplayer.%player's uuid%} parsed as offline player, player)
        if index of event-slot = 13:
            execute player command "mute %{punishedplayer.%player's uuid%}% Racism/Discrimination"
            execute player command "tempban -s %{punishedplayer.%player's uuid%}% 1h Racism/Discrimination"
        if index of event-slot = 15:
            execute player command "lockaccount %{punishedplayer.%player's uuid%}%"
on inventory click:
    if name of event-inventory is "&cPunish Player":
        cancel event
    if name of event-inventory is "&c&lBug Abusing":
        cancel event
    if name of event-inventory is "&c&lChat Abuse":
        cancel event


on inventory click:
    if name of event-inventory is "&cPast Punishments":
        cancel event 
on first join:
    set {sm::%player's uuid%.joindate} to now
on join:
    set {sm::%player's uuid%.lastjoin} to now
on left click with diamond axe:
    if name of tool is "&c&lBan Hammer":
        if player has permission "staff.member": #change this to staff mode future me :D
            set {_tp} to target player
            if {_tp} is not set:
                wait 1 tick
            else:
                cancel event
                send "&8You are punishing&c %target player%" to player
                set {_tp} to target player 
                wait 5 ticks
                execute player command "punish %{_tp}%"
on right click with diamond axe:
    if name of tool is "&c&lBan Hammer":
        if player has permission "staff.member": #change this to staff mode future me :D
            set {_tp} to target player
            if {_tp} is not set:
                wait 1 tick
            else:
                cancel event
                send "&8You are punishing&c %target player%" to player
                set {_tp} to target player 
                wait 5 ticks
                execute player command "punish %{_tp}%"

on damage:
    if name of attacker's tool is "&c&lBan Hammer":
        if {staffmode::*} contains attacker's uuid:
            if victim is a player:
                cancel event
                send "&8You are punishing&c %victim%" to attacker
                execute attacker command "punish %victim%"

on left click with ice:
    if name of tool is "&b&lFreeze Player":
        if player has permission "staff.member": #change this to staff mode future me :D
            set {_target} to target player
            if {_target} is not set:
                wait 1 tick
            else:
                cancel event
                set {_target} to target player 
                wait 5 ticks
                execute player command {@freezecommand}
on right click with ice:
    if {cooldown.%player's name%} is not set:
        if name of tool is "&b&lFreeze Player":
            if player has permission "staff.member": #change this to staff mode future me :D
                set {_target} to target player
                if {_target} is not set:
                    wait 1 tick
                else:
                    if {cooldown.%player's name%} is not set:
                        cancel event
                        set {_target} to target player 
                        wait 5 ticks
                        execute player command {@freezecommand}
                        set {cooldown.%player's name%} to "true"
                        wait 1 second
                        delete {cooldown.%player's name%}

on damage:
    name of attacker's tool is "&b&lFreeze Player"
    attacker has permission "staff.member"
    cancel event
    set {_target} to victim's name
    execute attacker command {@freezecommand}
on right click with light green dye:
    if name of player's tool is "&a&lVanish":
        if player has permission "staff.member":
            reveal player to all players
            set slot 8 of player's inventory to a gray dye named "&a&lVanish" with lore "&7Status: &cDisabled"
            set {vanish.%player's uuid%} to false
            loop all players:
                if loop-player has permission "staff.member":
                    send "&bVanish &8| &3%player's name%&b unvanished!" to loop-player
on right click with gray dye:
    if name of player's tool is "&a&lVanish":
        if player has permission "staff.member":
            hide player from all players
            set slot 8 of player's inventory to a light green dye named "&a&lVanish" with lore "&7Status: &aEnabled"
            set {vanish.%player's uuid%} to true
            loop all players:
                if loop-player has permission "staff.member":
                    send "&bVanish &8| &3%player's name%&b vanished!" to loop-player
                    reveal player to loop-player
on right click with potion of invisibility:
    if name of player's tool is "&f&lVanish":
        if player has permission "staff.member":
            execute player command "vanish"
            cancel event

on join:
    if {staffmode::*} contains player's uuid:
        wait 2 ticks
        send "&bYou are currently &3in staffmode&b!"
        clear player's inventory
        set slot 1 of player's inventory to a ice named "&b&lFreeze Player" with lore "&7Left Click on a player to freeze them"
        set slot 0 of player's inventory to a diamond axe named "&c&lBan Hammer" with lore "&7Left click on a player to punish them!"
        if {@vanish} is true:
            if {vanish.%player's uuid%} is not true:
                execute player command "vanish"
                if {vanish.%player's uuid%} is not true:
                    send "&CFailed &8|&c Failed to enable your &4Vanish&c! &cThis was likely due to the skript addon not being installed!" to player
            set slot 8 of player's inventory to a light green dye named "&a&lVanish" with lore "&7Status: &aEnabled"
        else:
            set slot 8 of player's inventory to a potion of invisibility named "&f&lVanish" with lore "&3Right click&b to use!"        
on leave:
    clear player's inventory
on drop:
    if {staffmode::*} contains player's uuid:
        cancel event
on inventory click:
    if {staffmode::*} contains player's uuid:
        cancel event
on block place:
    if {staffmode::*} contains player's uuid:
        cancel event
on block break:
    if {staffmode::*} contains player's uuid:
        cancel event
on pickup:
    if {staffmode::*} contains player's uuid:
        cancel event
on chat:
    set {_message} to message in lowercase #! All messages for the filter are parsed in lowercase!
    loop {filter::*}:
        if {_message} contains loop-value:
            if player doesn't have permission "filter.bypass":
                set {_blockedmessage} to loop-value
                cancel event
                send "&cBlocked &8| &cThe word &4%{_blockedmessage}%&c was blocked in your message!" to player
                send "&cBlocked &8| &cThe word &4%{_blockedmessage}%&c was blocked in &4%player's name%'s&c message!" to console
                play sound {@errorsound} with volume 2 and pitch 1 at player



on join:
    if {@actionbar} is true:
        while player is online:
            if {vanish.%player's uuid%} is true:
                set {_vanished} to "Enabled"
                wait 5 ticks
            else:
                set {_vanished} to "Disabled"
                wait 5 ticks
            if {staffmode::*} contains player's uuid:
                set {_sm} to "Enabled"
                wait 5 ticks
            else:
                set {_sm} to "Disabled"
                wait 1 second
            if {staffmode::*} contains player's uuid:
                if {@vanish} is true:
                    send actionbar "&3Ping: &b%player's ping% &8| &3Vanish: &b%{_vanished}% &8| &3Staffmode: &bEnabled" to player
                    wait 5 ticks
                else:
                    send actionbar "&3TPS: &b%tps from last minute% &8| &3Ping: &b%player's ping% &8| &3Staffmode: &bEnabled" to player
                    wait 5 ticks  
            else:
                wait 5 ticks
on damage:
    if {@pvp} is false:
        if {staffmode::*} contains attacker's uuid:
            cancel event
on player walk:
    if {freeze.%player's uuid%} is true:
        cancel event
on chat:
    if {freeze.%player's uuid%} is true:
        cancel event
        send "&cError &8|&c You are currently &4frozen&c!" to player
on damage:
    if {staffmode::*} contains victim's uuid:
        cancel event        
# ╔───────────────────────────────────────────╗
# │ _____ _           _   _             _ _ _ │
# │|_   _| |__   __ _| |_( )___    __ _| | | |│
# │  | | | '_ \ / _` | __|// __|  / _` | | | |│
# │  | | | | | | (_| | |_  \__ \ | (_| | | |_|│
# │  |_| |_| |_|\__,_|\__| |___/  \__,_|_|_(_)│
# ╚───────────────────────────────────────────╝
#Developed by PBSI, with help from LemonFrenzy! 
#Redistribution of the free version is allowed and appreciated! 
#For help contact me on Discord: pbsi
#Inspirational Quotes:
# "skript is trash" -DGBFounder
# "He's right skript isn't that good" -Azex
# "yeah skript seems useless to me" -Wally
# "Skript is dogs**t" -Luis
# "skript sucks anyway" -Srnyx
